name: NoLexa Bug Report
description: Report a bug found in NoLexa.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Please explain what happened when the bug happened.
      value: "Type here..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Current Version
      description: What version of NoLexa are you running?
      options:
        - 0.0.1 Preview
        - 0.0.1
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Current OS
      description: What Operating System are you using?
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 8.1/8
        - Windows 7
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
