name: NoLexa Bug Report
description: Report a bug found in NoLexa.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report. This helps make NoLexa a more stable application.
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Details
      description: Please give us information before the bug happened, and what you were doing.
      placeholder: I was doing something, and something happened.
      value: "!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Current Version
      description: What version of our software are you running?
      options:
        - 0.0.1 Preview
        - 0.0.1
        - Other
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What OS are you currently using?
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 8.1/8
        - Windows 7
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: replicate
    attributes:
      label: Reproduce Bug
      description: Are you able to successfully reproduce the bug?
      options:
        - Yes, I can replicate the bug.
        - No, I cannot replicate the bug.
    validations:
      required: true
